security.jwt.token.secret-key: my-secret-key

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ciejmuciej@gmail.com
    password: ibsw qmai bgod esqm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/laboratory
    username: root
    password: d31f2547
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      show:
        sql: true
      ddl-auto: create